baseurl = "http://juliusreade.com/"
languageCode = "en-us"
title = "Julius Reade: Somebody Please Help Me"
theme = "reade"

[taxonomies]
tag = "tags"
category = "categories"

[params]
  Author = "Julius Reade"
  
[permalinks]
  blog = "/:year/:month/:day/:title/"
