baseurl = "https://juliusreade.com/"
languageCode = "en-us"
title = "I Don't Know Who You Are"
theme = "reade"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
description = "Your Digital Heart Attack. Something Fancy Like Cheap Roses, Piltering Without Grace."


disqusShortname = "juliusreade"
	disqus_url = "https://juliusreade.disqus.com/"

[author]
	name = "Julius Reade"


[taxonomies]
	tag = "tags"
	category = "categories"
  

[permalinks]
	blog = "/:year/:month/:day/:title/"
	adelaidesucks = "/adelaidesucks/:title/"


