baseurl = "https://juliusreade.com/"
languageCode = "en-us"
title = ""  
theme = "reade"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
description = "Human expression."


disqusShortname = "juliusreade"
	disqus_url = "https://juliusreade.disqus.com/"

[author]
	name = "Julius Reade"


[taxonomies]
	tag = "tags"
	category = "categories"
  

[permalinks]
	blog = "/:year/:month/:day/:title/"
	adelaidesucks = "adelaidesucks/:title/"


