baseurl = "https://juliusreade.com/"
languageCode = "en-us"
title = "Julius Reade: Somebody Please Help Me"
theme = "reade"


disqusShortname = "juliusreade"
	disqus_url = "https://juliusreade.disqus.com/"


[taxonomies]
tag = "tags"
category = "categories"


[permalinks]
  blog = "/:year/:month/:day/:title/"

